### ISSUE TITLE
Wrong main script in package.json

### ISSUE THREAD

**Issue by michalvankodev** [TylorS/cycle-history#1]
There is no such file that you refer in package.json as a main file. Therefore is really hard to import your lib.

**Comment by TylorS** [comment]
I solved this with npm version 0.3.3 ~40 minutes ago :+1:

**Comment by michalvankodev** [comment]
I've downloaded ~hour ago

**Comment by TylorS** [comment]
Let me know if you have anymore issues, it was a goof on my part that made it stop working (version 0.3.0) to begin with.
